spring.application.name=GitLab-Scanner
server.port=8080
server.servlet.context-path=/

# GitLab Configuration
gitlab.api.url=https://gitlab.com/api/v4
gitlab.token=${GITLAB_TOKEN:glpat-lSlFduNfZgqBecZ9MvSKo2M6MQpvOjEKdTo1bnVsZg8.01.170lw8qyl}

# Actuator Configuration for Health Checks
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Thymeleaf Configuration
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

# Logging
logging.level.root=INFO
logging.level.com.example.gitlabscanner=INFO

# OpenAPI/Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
